#ifndef __TUYA_GW_TRD_GW_PARTY_CLUSTER_SCHNEIDER_H__
#define __TUYA_GW_TRD_GW_PARTY_CLUSTER_SCHNEIDER_H__
#include "tuya_gw_trd_party_cfg.h"
#include "tuya_z3_base.h"

#if defined (TUYA_GW_THIRD_PARTY_SCHNEIDER_SUPPORT) && (1 == TUYA_GW_THIRD_PARTY_SCHNEIDER_SUPPORT)

#define SND_ZCL_MANU_CODE 0x105E

#define SND_ZCL_VISA_CONFIG_CLUSTER_ID  0xFC04

/**** SND_ZCL_VISA_CONFIG_CLUSTER_ID  0xFC01 ****/
#define SND_ATTR_INDICATOR_LEVEL    0x0000 //指示灯亮度
#define SND_ATTR_INDICATOR_COLOR    0x0001 //指示灯颜色
#define SND_ATTR_INDICATOR_MODE     0x0002 //指示灯模式
#define SND_ATTR_CURTAIN_MODE_1     0x0003 //窗帘1工作模式
#define SND_ATTR_CURTAIN_MODE_2     0x0004 //窗帘2工作模式
#define SND_ATTR_CURTAIN_STAT_1     0x0005 //窗帘1运行状态
#define SND_ATTR_CURTAIN_STAT_2     0x0006 //窗帘2运行状态

#endif //TUYA_GW_THIRD_PARTY_SCHNEIDER_SUPPORT
#endif // __TUYA_GW_TRD_GW_PARTY_CLUSTER_SCHNEIDER_H__
